apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: grafana-dashboard-sock-shop
    files:
      - sock-shop-nkp.json=../../sock-shop/observability/sock-shop-nkp.json

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard_kommander: "1"
