apiVersion: apps.kommander.d2iq.io/v1alpha3
kind: AppDeployment
metadata:
  name: prometheus-thanos-traefik
  namespace: other-project-rxmz5
spec:
  appRef:
    appID: prometheus-thanos-traefik
    kind: ClusterApp
    name: prometheus-thanos-traefik-0.0.5
  clusterConfigOverrides:
    - appVersion: 0.0.5
      clusterSelector:
        matchExpressions:
          - key: kommander.d2iq.io/cluster-name
            operator: In
            values:
              - nkp-demo-01
      configMapName: ""
  clusterSelector:
    matchExpressions:
      - key: kommander.d2iq.io/cluster-name
        operator: In
        values:
          - nkp-demo-01
